### ISSUE TITLE
[Chore] Repo name change; Project name change

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-traefik-mesh#57]
**Description**
Maesh changed it's name to Traefik Mesh. This repo and name of the Meshery adapter needs updated to reflect this change.

**Comment by leecalcote** [comment]
@layer5io/adapter-maintainers FYI. Repo name changing now.

**Comment by utkarsh-pro** [comment]
@leecalcote can we close this issue now?

**Comment by leecalcote** [comment]
Sounds good
