### ISSUE TITLE
[CI] No image for layer5/meshery-traefik-mesh on docker hub

### ISSUE THREAD

**Issue by utkarsh-pro** [layer5io/meshery-traefik-mesh#65]
**Description**

Running `docker pull layer5/meshery-traefik-mesh` results in:
```
Using default tag: latest
Error response from daemon: manifest for layer5/meshery-traefik-mesh:latest not found: manifest unknown: manifest unknown
```

Running `docker pull layer5/meshery-traefik-mesh:stable-latest` results in:
```
Error response from daemon: manifest for layer5/meshery-traefik-mesh:stable-latest not found: manifest unknown: manifest unknown
```

**Expected Behavior**

`docker pull layer5/meshery-traefik-mesh:stable-latest` should be able to pull in the image successfully.

**Comment by utkarsh-pro** [comment]
@leecalcote, I think last github actions skipped pushing image to the registry https://github.com/layer5io/meshery-traefik-mesh/pull/64/checks?check_run_id=1646137891 probably because it wasn't a "release".

I am not sure if starting the actions again will push the image properly.

**Comment by leecalcote** [comment]
Cutting a new release....

**Comment by leecalcote** [comment]
How did we do with the latest release?

**Comment by utkarsh-pro** [comment]
@leecalcote, it didn't work. That's one of the things I wanted to discuss. https://hub.docker.com/r/layer5/meshery-traefik-mesh/tags?page=1&ordering=last_updated there are no releases here.

**Comment by utkarsh-pro** [comment]
@leecalcote closing this as this has been fixed.
