### ISSUE TITLE
Logo missing in Adapter Chip in Meshery UI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-traefik-mesh#77]
**Description**
In the last release of this adapter, the icon in the adapter chip has gone missing.

**Expected Behavior**
Should show a Traefik Mesh icon.

**Screenshots**
<img width="240" alt="Screen Shot 2021-04-13 at 9 13 02 PM" src="https://user-images.githubusercontent.com/7570704/114644480-35b84780-9c9d-11eb-910e-375596c6ab58.png">

**Environment:**
- Host OS: 
- Meshery Version: v0.5.2
- Kubernetes Version: 
- Browser:

**Comment by kumarabd** [comment]
https://github.com/layer5io/meshery/pull/2715
